from colorama import Back

headers = {'User-Agent': 'PostmanRuntime/7.29.2'}

CARRY_BACKGROUND = Back.GREEN
SUP_BACKGROUND = Back.CYAN
HERO_BACKGROUND = Back.RED
C_BG = Back.RESET 

GOLD_FIRST_LIMIT = 500
GOLD_SECOND_LIMIT = 649
EXP_FIRST_LIMIT = 500
EXP_SECOND_LIMIT = 649
PARTICIPATION_FIRST_LIMIT = 50
PARTICIPATION_SECOND_LIMIT = 63

GOLD_PUNISHMENT = 20
GOLD_AWARD_COFFICIENT = 10
EXP_PUNISHMENT = 20
EXP_AWARD_COFFICIENT = 10
DAMAGE_1_DIVIDER = 1000
DAMAGE_1_AWARD_COFFICIENT = 3
DAMAGE_2_DIVIDER = 1000
DAMAGE_2_AWARD_COFFICIENT = 3
DAMAGE_3_DIVIDER = 1000
DAMAGE_3_AWARD_COFFICIENT = 1
CARRY_LANE_LOSE_PUNISHMENT = 10
CARRY_LANE_WIN_AWARD = 20
SUP_LANE_LOSE_PUNISHMENT = 30
SUP_LANE_WIN_AWARD = 30
PARTICIPATION_PUNISHMENT = 30
PARTICIPATION_AWARD_COFFICIENT = 4